use_frameworks!

target 'SwiftCodeBuilder_Example' do
  pod 'SwiftCodeBuilder', :path => '../'

  target 'SwiftCodeBuilder_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
